version: "3.2"

services:
  rrdcached:
    image: kadock/rrdcached
    container_name: rrdcached
    ports:
      - target: 42217
        published: 42217
        protocol: udp
    volumes:
      - "rrdcached_db:/var/lib/rrdcached/db/"
      - "rrdcached_journal:/var/lib/rrdcached/journal/"
      - "rrdcached_sock:/run/rrdcached/"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - "TZ=Europe/Copenhagen"
      - "RRDCACHED_LOGLEVEL=LOG_INFO"
      - "RRDCACHED_WRITE_TIMEOUT=300"
      - "RRDCACHED_THREADS=4"
      - "RRDCACHED_FLUSH_TIMEOUT=3600"
    restart: always

volumes:
  rrdcached_db:
  rrdcached_journal:
  rrdcached_sock:
